### ISSUE TITLE
Notably v1.4 Deliverables (By 13-04)

### ISSUE THREAD

**Issue by kevinputera** [AY1920S2-CS2103T-W17-2/main#380]
Deliverables for each person for v1.4 milestone (**please finish before code-related by Friday 10/04, documentation/code quality/logging by 13/04 midnight!**) 

@AY1920S2-CS2103T-W17-2/developers :
- [ ] Create a v1.4 release
- [ ] Release a v1.4 JAR

@firzanarmani :
- [x] Title allow for symbols (#412)
- [x] Case insensitive comparison (equals) for Title equalsIgnoreCase() (#410)
- [ ] Improve UG DG
- [x] Prevent navigating of root when block tree is not empty (#427)
   - Set body of root to be “create a new note to begin!”
- [ ] UG needs to explain that we’re only displaying three levels of notes in the sidebar (https://github.com/AY1920S2-CS2103T-W17-2/main/issues/371)
- [x] Unknown creation bug (https://github.com/AY1920S2-CS2103T-W17-2/main/issues/354)

@johannagwan :
- [x] Move responseText to ViewStateModel
- [x] Create TestUtil class to remove code duplication for the test cases for:
   - [x] Sug Cmds
   - [x] Sug Cmd Parsers
   - [x] Sug Engine Impl
- [x] Improve test cases
- [x] More comprehensive error message to the user
- [x] Search Sug Cmd Parser (“searching for keyword: …)
- [x] Add shorthands for Sug Commands and Sug Engine Impl
- [x] Update Sug Cmd Parsers to pass a list of results to the sug commands
- [x] For all commands: integrate user input into the message. E.g. “Create new note entitled …”
- [x] Improve code quality
   - [x] Search Sug Cmd
- [x] UG typo (https://github.com/AY1920S2-CS2103T-W17-2/main/issues/357, https://github.com/AY1920S2-CS2103T-W17-2/main/issues/366)

@ljiazh3ng :
- [x] More comprehensive error message to the user(Using responseText)
- [ ] Improve code quality on test case(Same as Jo)
- [ ] Add parser DG
- [ ] Improve path’s explanation in DG
- [x] Logic method for editing block’s content (for edit modal)
- [x] Disable case-sensitivity in path, update UG to reflect this (https://github.com/AY1920S2-CS2103T-W17-2/main/issues/351)

@HemanshuGandhi :
- [x] Implement Edit Display Modal***
   - Separate Title and Body sections.
- [x] Enable Enter (Tab)  selection of Suggestions Items**
   - Make sure suggestion items are traversable using arrow keys directly from inside command input
- [x] Hide "Root"
- [x] Improve UI for Response text 
- [x] Bug Fix: disable click event on sideBar.
- [x] Improve UI. In particular, color theme and suggestion Items
- [x] Add path to block content display view (see b)
- [x] UI Test cases/assertions/Defensive Programming/logging
- [ ] Update View diagram in DG (Ui.png, with cleaner lines)
- [ ] UG: guide user through experience of editing a note. 

@kevinputera :
- [x] Fix bugs in correction engine’s forward matching feature (#333, #388)
- [x] Make correction engine returns a list of results (if there are multiple possibilities with the same distance)
- [x] Move out CorrectionEngine dependency to Parser’s and SuggestionEngine’s level, rather than CommandParser’s and SuggestionCommandParser’s level.
- [x] Improve logging across CorrectionEngine and Compiler
- [x] Improve test coverage of Compiler
- [ ] Improve DG’s explanation on correction engine + markdown spec
- [ ] Improve UG’s explanation on correction engine + markdown compiler
- [ ] Work on my PPP (portfolio)
- [ ] Finish up Markdown to HTML compiler
- [ ] Work on demo for correction engine (need to clearly separate the role of suggestion engine/parser from correction engine) + markdown compiler
